name: Aseprite Debugger Extension Publish
run-name: ${{ github.ref_name }} Publish

on:
    release:
        types: [published]

jobs:
    package_extension:
        name: Package Extension
        runs-on: windows-latest
        steps:
          - name: Checkout Repo
            id: checkout_repo
            uses: actions/checkout@v4
            with:
              submodules: recursive
              
          - name: npm
            uses: actions/setup-node@v4
            with:
              node-version: 18.x

          - name: Install Dependencies
            run: npm install

          - name: Package Extension
            run: npx vsce package -o ${{ vars.EXT_NAME }}.vsix

          - name: Upload Extension
            uses: actions/upload-artifact@v3
            with:
              name: "extension"
              path: "*.vsix"
              retention-days: 2
        
    upload_extension:
        name: Upload Extension
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: package_extension
        steps:
          - name: Retreive Extension Artifact
            id: retreive_extension_artifact
            if: success()
            uses: actions/download-artifact@v3
            with:
              name: "extension"

          - name: Retrieve Release
            id: retrieve_release
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}

          - name: Upload Asset
            id: upload_asset 
            run: |
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ fromJson(steps.retrieve_release.outputs.data).id }}/assets?name=${{ vars.EXT_NAME }}.vsix" \
              --data-binary "@${{ vars.EXT_NAME }}.vsix"

    publish_extension:
        name: Publish Extension
        runs-on: ubuntu-latest
        needs: package_extension
        steps:
          - name: Retreive Extension Artifact
            id: retreive_extension_artifact
            if: success()
            uses: actions/download-artifact@v3
            with:
              name: "extension"

          - name: Retrieve Release
            id: retrieve_release
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}

          - name: Publish Extension
            id: publish_extension
            env:
              VSCE_PAT: ${{ secrets.VSCE_PAT }}
            run: npx vsce publish --packagePath ${{ vars.EXT_NAME }}.vsix

        
