name: Aseprite Debugger Extension Publish
run-name: ${{ github.ref_name }} Publish

on:
    release:
        types: [published]

jobs:
    package_extension:
        name: Publish Extension
        runs-on: windows-latest
        permissions:
            contents: write
        steps:
          - name: Checkout Repo
            id: checkout_repo
            uses: actions/checkout@v4
            with:
              submodules: recursive
              
          - name: npm
            uses: actions/setup-node@v2
            with:
              node-version: 18.x

          - name: Install Dependencies
            run: npm install

          - name: Package Extension
            run: npx vsce package

          - name: Upload Extension
            uses: actions/upload-artifact@v2
            with:
              name: "extension"
              path: "*.vsix"
                
